# i3bar — hacker theme
bar {
        status_command i3status -c ~/.config/i3status/config
        separator_symbol " · "
        colors {
                background #000000
                statusline #00ff00
                separator  #007700

                # class            border  backgr  text
                focused_workspace  #00ff00 #003300 #00ff00
                active_workspace   #007700 #001100 #00bb00
                inactive_workspace #004400 #000000 #007700
                urgent_workspace   #ff0000 #330000 #ff5555
        }
}
