# i3bar — hacker theme
bar {
        status_command i3status -c ~/.config/i3status/config
        separator_symbol " · "
        colors {
                background #000000
                statusline #00ff00
                separator  #003300

                # class            border  backgr  text
                focused_workspace  #00ff00 #001a00 #00ff00
                active_workspace   #003300 #000000 #005500
                inactive_workspace #001a00 #000000 #003300
                urgent_workspace   #ff0000 #000000 #ff0000
        }
}
